[project]
name = "02-image-text-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic==2.13.4",
    "pyside6==6.11.1",
]

[dependency-groups]
dev = [
    "black==26.5.1",
    "poethepoet>=0.48.0",
    "pytest==8.1.1",
    "ruff==0.3.4",
]

[tool.poe.tasks]
format = "ruff format ."
lint = "ruff check ."
start = "python src/main.py"
test = "pytest"
